name: mediapipe_env
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.9
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - ipykernel=6.30.1
  - numpy==2.0.2
  - pandas=2.3.1
  - scikit-learn=1.6.1
  - plotly=6.3.0
  - openpyxl=3.1.5
  - pip:
      - absl-py==2.3.1
      - anyio==4.11.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bleach==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - charset-normalizer==3.4.3
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.17
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - fastjsonschema==2.21.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - fqdn==1.5.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - ipython==8.18.1
      - isoduration==20.11.0
      - jax==0.4.30
      - jaxlib==0.4.30
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.9
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lark==1.3.0
      - markupsafe==3.0.3
      - matplotlib==3.9.4
      - mediapipe==0.10.21
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - notebook==7.4.7
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.12.0.88
      - opt-einsum==3.4.0
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pipdeptree==2.28.0
      - platformdirs==4.4.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.0
      - pycparser==2.23
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-json-logger==3.3.0
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.1
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - sounddevice==0.5.2
      - soupsieve==2.8
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - tornado==6.5.2
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20250822
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - xlsxwriter==3.2.9
      - zipp==3.23.0


